/* XPM */
static char *network[] = {
/* width height num_colors chars_per_pixel */
"    48    48       10            1",
/* colors */
". m mask c none",
"# c #ffffff",
"a c #aaa2a2",
"b c #817979",
"c c #183c59",
"d c #615959",
"e c #ff6145",
"f c #c6bebe",
"g c #ffff00",
"h c #fff7f7",
/* pixels */
"................................................",
"................................................",
".......#aaaaab..................................",
"..#################.............................",
"..#bbbbbbbbbbbbbbbb.............................",
"..#bccccccccccccc#b.............................",
"..#bcbbcbcbbccccc#b.............................",
"..#bccccccccccccc#b.............................",
"..#bcbcbbcccccccc#bdddddddd.....................",
"..#bccccccccccccc#beeffffffddd..................",
"..#bcbcbccccccccc#beegggggffffdd................",
"..#bccccccccccccc#beedddddgggffadb..............",
"..#bcbbbcbccccccc#b######ddddggfaab.............",
"..#bccccccccccccc#b......###dddggaaf............",
"..#bccccccccccccc#b.........##dddgaaf...........",
"..#b##############b...........##bbgabf..........",
"..#bbbbbbbbbbbbbbbb.............#ffgb#..........",
"......ddddddddd..................bfgb#..........",
".....##aaaaaaabb.................bfgb#..........",
"...##chchchchchcbb..............bbfgb#..........",
".##achchchchcachcabb..........ddfffgb#..........",
".aaaaaaaaaaaaaaaaaab.....dddddfffggbb#..........",
".ddddddddddddddddddddddddffffffggbbb#...........",
".............ddddfffffffffgggggbbb##............",
"...........ddfffffggggggggbbbbbb##..............",
".........ddfffggggddddddddd#####.#aaaaab........",
"........dfffggdddd#########.#################...",
".......dffggdd####..........#bbbbbbbbbbbbbbbb...",
"......dffgdd##..............#bccccccccccccc#b...",
"......dfgdd#................#bcbbcbcbbccccc#b...",
"......dfgd#.................#bccccccccccccc#b...",
"......dfgd#.................#bcbcbbcccccccc#b...",
"......dfgdbd................#bccccccccccccc#b...",
"......dffgbbd...............#bcbcbccccccccc#b...",
".......aaagbbddd............#bccccccccccccc#b...",
"........faaggbbbdd..........#bcbbbcbccccccc#b...",
".........fbbbggfffdddd......#bccccccccccccc#b...",
"..........f#bbbggfffffdddddd#bccccccccccccc#b...",
"............##bbbggggfffffee#b##############b...",
"..............##bbbbbgggggee#bbbbbbbbbbbbbbbb...",
"................####bbbbbbee....ddddddddd.......",
"....................########...##aaaaaaabb......",
".............................##chchchchchcbb....",
"...........................##achchchchcachcabb..",
"...........................aaaaaaaaaaaaaaaaaab..",
"...........................ddddddddddddddddddd..",
"................................................",
"................................................"};
