#!/bin/sh
#
#  gxfce
#
#  Copyright (C) 1999 Olivier Fourdan (fourdan@xfce.org)
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#
#
# xfce_install - set up XFce on a user account
#
#

BKUP=$HOME/.xfce_bkup
DATE=`date +%m%d%H%M%S`

# Check existance of $BKUP directory
# and create it if it does not exist

if [ ! -d $BKUP ]; then
	mkdir $BKUP
fi

if [ -f $HOME/.gtkrc ]; then
	mv -f $HOME/.gtkrc $BKUP/.gtkrc.$DATE 2>/dev/null
	echo An existing file $HOME/.gtkrc has been moved to $BKUP/.gtkrc.$DATE
fi

echo Upgrade complete
exit 0
